# Builds the IOTC data validator UI for ARM machines, for which the rocker/shiny image cannot be used...
docker build --build-arg BB_user=%BITBUCKET_USER% --build-arg BB_password=%BITBUCKET_PASSWORD% -t iotc/validator-ui-arm:0.1.0-interim -f Dockerfile.arm --progress=plain .
